name: Build and Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build
  
      - name: Connect to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}

      - name: Deploy build to EC2
        run: |
          scp -r build/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/react-app
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "pm2 restart react-app"

